include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style
    - prefer_const_constructors: true
    - prefer_const_constructors_in_immutables: true
    - prefer_const_literals_to_create_immutables: true
    - prefer_final_locals: true
    - prefer_final_fields: true
    - prefer_final_in_for_each: true
    - prefer_relative_imports: true
    - use_key_in_widget_constructors: true
    
    # Good practices
    - avoid_print: false  # Allowed for debugging
    - avoid_unnecessary_containers: true
    - avoid_web_libraries_in_flutter: true
    - avoid_empty_else: true
    - avoid_init_to_null: true
    - avoid_null_checks_in_equality_operators: true
    - avoid_relative_lib_imports: true
    - avoid_return_types_on_setters: true
    - avoid_unused_constructor_parameters: true
    - avoid_void_async: true
    - cancel_subscriptions: true
    - cascade_invocations: true
    - comment_references: true
    - control_flow_in_finally: true
    - depend_on_referenced_packages: true
    - empty_catches: true
    - empty_constructor_bodies: true
    - library_names: true
    - library_prefixes: true
    - no_duplicate_case_values: true
    - no_logic_in_create_state: true
    - no_runtimeType_toString: true
    - null_closures: true
    - overridden_fields: true
    - package_api_docs: true
    - prefer_adjacent_string_concatenation: true
    - prefer_asserts_in_initializer_lists: true
    - prefer_conditional_assignment: true
    - prefer_contains: true
    - prefer_equal_for_default_values: true
    - prefer_final_parameters: true
    - prefer_foreach: true
    - prefer_if_null_operators: true
    - prefer_inlined_adds: true
    - prefer_is_empty: true
    - prefer_is_not_empty: true
    - prefer_is_not_operator: true
    - prefer_single_quotes: true
    - prefer_spread_collections: true
    - recursive_getters: true
    - sized_box_for_whitespace: true
    - sort_child_properties_last: true
    - type_init_formals: true
    - unawaited_futures: true
    - unnecessary_brace_in_string_interps: true
    - unnecessary_const: true
    - unnecessary_getters_setters: true
    - unnecessary_lambdas: true
    - unnecessary_new: true
    - unnecessary_null_checks: true
    - unnecessary_null_in_if_null_operators: true
    - unnecessary_overrides: true
    - unnecessary_parenthesis: true
    - unnecessary_this: true
    - unrelated_type_equality_checks: true
    - use_build_context_synchronously: true
    - use_full_hex_values_for_flutter_colors: true
    - use_rethrow_when_possible: true
    - use_setters_to_change_properties: true
    - use_string_buffers: true
    - valid_regexps: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/test/**"
    - "**/integration_test/**"
  errors:
    invalid_annotation_target: ignore
    
  strong-mode:
    implicit-casts: true
    implicit-dynamic: false

  language:
    strict-inference: true
    strict-raw-types: true

  experimental:
    super-invocation: true